/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.data_model;
@org.apache.avro.specific.AvroGenerated
public enum FdsEventEnum implements org.apache.avro.generic.GenericEnumSymbol<FdsEventEnum> {
  ANX_EVENT_TYPE, DNX_EVENT_TYPE, UMBRA_EVENT_TYPE, PENUMBRA_EVENT_TYPE, ECLIPSE_EVENT_TYPE, SUNLIGHT_EVENT_TYPE, AOS_EVENT_TYPE, LOS_EVENT_TYPE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FdsEventEnum\",\"namespace\":\"com.incomplete.cubegs.common.avro.data_model\",\"symbols\":[\"ANX_EVENT_TYPE\",\"DNX_EVENT_TYPE\",\"UMBRA_EVENT_TYPE\",\"PENUMBRA_EVENT_TYPE\",\"ECLIPSE_EVENT_TYPE\",\"SUNLIGHT_EVENT_TYPE\",\"AOS_EVENT_TYPE\",\"LOS_EVENT_TYPE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
