#ifndef __MODULESTATUSENUM_H_INCLUDED__
#define __MODULESTATUSENUM_H_INCLUDED__

enum ModuleStatusEnum {
    MODE_NONE = 0,
    MODE_NOT_RUNNING = 1,
    MODE_RUNNING = 2
};

#endif // __MODULESTATUSENUM_H_INCLUDED__
