/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** This message indicates there is no more messages or data. It contains no comma at the end */
@org.apache.avro.specific.AvroGenerated
public class AvroNone extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5267842720193075976L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroNone\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"This message indicates there is no more messages or data. It contains no comma at the end\",\"fields\":[{\"name\":\"none_field\",\"type\":\"int\",\"doc\":\"End of include files\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroNone> ENCODER =
      new BinaryMessageEncoder<AvroNone>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroNone> DECODER =
      new BinaryMessageDecoder<AvroNone>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AvroNone> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AvroNone> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AvroNone> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroNone>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AvroNone to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AvroNone from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AvroNone instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AvroNone fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** End of include files */
  private int none_field;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroNone() {}

  /**
   * All-args constructor.
   * @param none_field End of include files
   */
  public AvroNone(java.lang.Integer none_field) {
    this.none_field = none_field;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return none_field;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: none_field = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'none_field' field.
   * @return End of include files
   */
  public int getNoneField() {
    return none_field;
  }


  /**
   * Sets the value of the 'none_field' field.
   * End of include files
   * @param value the value to set.
   */
  public void setNoneField(int value) {
    this.none_field = value;
  }

  /**
   * Creates a new AvroNone RecordBuilder.
   * @return A new AvroNone RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.AvroNone.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.AvroNone.Builder();
  }

  /**
   * Creates a new AvroNone RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroNone RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.AvroNone.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.AvroNone.Builder other) {
    if (other == null) {
      return new com.incomplete.cubegs.common.avro.messages.AvroNone.Builder();
    } else {
      return new com.incomplete.cubegs.common.avro.messages.AvroNone.Builder(other);
    }
  }

  /**
   * Creates a new AvroNone RecordBuilder by copying an existing AvroNone instance.
   * @param other The existing instance to copy.
   * @return A new AvroNone RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.AvroNone.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.AvroNone other) {
    if (other == null) {
      return new com.incomplete.cubegs.common.avro.messages.AvroNone.Builder();
    } else {
      return new com.incomplete.cubegs.common.avro.messages.AvroNone.Builder(other);
    }
  }

  /**
   * RecordBuilder for AvroNone instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroNone>
    implements org.apache.avro.data.RecordBuilder<AvroNone> {

    /** End of include files */
    private int none_field;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.AvroNone.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.none_field)) {
        this.none_field = data().deepCopy(fields()[0].schema(), other.none_field);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing AvroNone instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.AvroNone other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.none_field)) {
        this.none_field = data().deepCopy(fields()[0].schema(), other.none_field);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'none_field' field.
      * End of include files
      * @return The value.
      */
    public int getNoneField() {
      return none_field;
    }


    /**
      * Sets the value of the 'none_field' field.
      * End of include files
      * @param value The value of 'none_field'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.AvroNone.Builder setNoneField(int value) {
      validate(fields()[0], value);
      this.none_field = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'none_field' field has been set.
      * End of include files
      * @return True if the 'none_field' field has been set, false otherwise.
      */
    public boolean hasNoneField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'none_field' field.
      * End of include files
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.AvroNone.Builder clearNoneField() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroNone build() {
      try {
        AvroNone record = new AvroNone();
        record.none_field = fieldSetFlags()[0] ? this.none_field : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroNone>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroNone>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroNone>
    READER$ = (org.apache.avro.io.DatumReader<AvroNone>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.none_field);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.none_field = in.readInt();

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.none_field = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










