/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** This message contains a generic error response to any message. It contains; code - return code. 0 means no   error message - error message  */
@org.apache.avro.specific.AvroGenerated
public class MsgErrorData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8023327194735455101L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsgErrorData\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"This message contains a generic error response to any message. It contains; code - return code. 0 means no   error message - error message \",\"fields\":[{\"name\":\"error_code\",\"type\":\"int\",\"doc\":\"Error code\"},{\"name\":\"error_message\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Error message\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MsgErrorData> ENCODER =
      new BinaryMessageEncoder<MsgErrorData>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MsgErrorData> DECODER =
      new BinaryMessageDecoder<MsgErrorData>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MsgErrorData> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MsgErrorData> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MsgErrorData> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MsgErrorData>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MsgErrorData to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MsgErrorData from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MsgErrorData instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MsgErrorData fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Error code */
  private int error_code;
  /** Error message */
  private java.lang.String error_message;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MsgErrorData() {}

  /**
   * All-args constructor.
   * @param error_code Error code
   * @param error_message Error message
   */
  public MsgErrorData(java.lang.Integer error_code, java.lang.String error_message) {
    this.error_code = error_code;
    this.error_message = error_message;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return error_code;
    case 1: return error_message;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: error_code = (java.lang.Integer)value$; break;
    case 1: error_message = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'error_code' field.
   * @return Error code
   */
  public int getErrorCode() {
    return error_code;
  }


  /**
   * Sets the value of the 'error_code' field.
   * Error code
   * @param value the value to set.
   */
  public void setErrorCode(int value) {
    this.error_code = value;
  }

  /**
   * Gets the value of the 'error_message' field.
   * @return Error message
   */
  public java.lang.String getErrorMessage() {
    return error_message;
  }


  /**
   * Sets the value of the 'error_message' field.
   * Error message
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.String value) {
    this.error_message = value;
  }

  /**
   * Creates a new MsgErrorData RecordBuilder.
   * @return A new MsgErrorData RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder();
  }

  /**
   * Creates a new MsgErrorData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MsgErrorData RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder other) {
    if (other == null) {
      return new com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder();
    } else {
      return new com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder(other);
    }
  }

  /**
   * Creates a new MsgErrorData RecordBuilder by copying an existing MsgErrorData instance.
   * @param other The existing instance to copy.
   * @return A new MsgErrorData RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgErrorData other) {
    if (other == null) {
      return new com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder();
    } else {
      return new com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder(other);
    }
  }

  /**
   * RecordBuilder for MsgErrorData instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsgErrorData>
    implements org.apache.avro.data.RecordBuilder<MsgErrorData> {

    /** Error code */
    private int error_code;
    /** Error message */
    private java.lang.String error_message;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.error_code)) {
        this.error_code = data().deepCopy(fields()[0].schema(), other.error_code);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.error_message)) {
        this.error_message = data().deepCopy(fields()[1].schema(), other.error_message);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing MsgErrorData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgErrorData other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.error_code)) {
        this.error_code = data().deepCopy(fields()[0].schema(), other.error_code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.error_message)) {
        this.error_message = data().deepCopy(fields()[1].schema(), other.error_message);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'error_code' field.
      * Error code
      * @return The value.
      */
    public int getErrorCode() {
      return error_code;
    }


    /**
      * Sets the value of the 'error_code' field.
      * Error code
      * @param value The value of 'error_code'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder setErrorCode(int value) {
      validate(fields()[0], value);
      this.error_code = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'error_code' field has been set.
      * Error code
      * @return True if the 'error_code' field has been set, false otherwise.
      */
    public boolean hasErrorCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'error_code' field.
      * Error code
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder clearErrorCode() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'error_message' field.
      * Error message
      * @return The value.
      */
    public java.lang.String getErrorMessage() {
      return error_message;
    }


    /**
      * Sets the value of the 'error_message' field.
      * Error message
      * @param value The value of 'error_message'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder setErrorMessage(java.lang.String value) {
      validate(fields()[1], value);
      this.error_message = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'error_message' field has been set.
      * Error message
      * @return True if the 'error_message' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'error_message' field.
      * Error message
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgErrorData.Builder clearErrorMessage() {
      error_message = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MsgErrorData build() {
      try {
        MsgErrorData record = new MsgErrorData();
        record.error_code = fieldSetFlags()[0] ? this.error_code : (java.lang.Integer) defaultValue(fields()[0]);
        record.error_message = fieldSetFlags()[1] ? this.error_message : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MsgErrorData>
    WRITER$ = (org.apache.avro.io.DatumWriter<MsgErrorData>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MsgErrorData>
    READER$ = (org.apache.avro.io.DatumReader<MsgErrorData>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.error_code);

    out.writeString(this.error_message);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.error_code = in.readInt();

      this.error_message = in.readString();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.error_code = in.readInt();
          break;

        case 1:
          this.error_message = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










