/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** This message only contains the header of the received message in order to extract the identification of the message */
@org.apache.avro.specific.AvroGenerated
public class MsgReceivedHeader extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4300223501350808607L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsgReceivedHeader\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"This message only contains the header of the received message in order to extract the identification of the message\",\"fields\":[{\"name\":\"header\",\"type\":{\"type\":\"record\",\"name\":\"MsgHeader\",\"doc\":\"This message describes the header of a message\",\"fields\":[{\"name\":\"version\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Fix value; 1.0\"},{\"name\":\"msg_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique identifier of the message\"},{\"name\":\"msg_code\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"code of the operation to be executed\"},{\"name\":\"authentication_key\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Authentication code. Not used\"},{\"name\":\"execution_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique execution identifier\"},{\"name\":\"user_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique user identifier\"}]},\"doc\":\"Common messages header\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MsgReceivedHeader> ENCODER =
      new BinaryMessageEncoder<MsgReceivedHeader>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MsgReceivedHeader> DECODER =
      new BinaryMessageDecoder<MsgReceivedHeader>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MsgReceivedHeader> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MsgReceivedHeader> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MsgReceivedHeader> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MsgReceivedHeader>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MsgReceivedHeader to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MsgReceivedHeader from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MsgReceivedHeader instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MsgReceivedHeader fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Common messages header */
  private com.incomplete.cubegs.common.avro.messages.MsgHeader header;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MsgReceivedHeader() {}

  /**
   * All-args constructor.
   * @param header Common messages header
   */
  public MsgReceivedHeader(com.incomplete.cubegs.common.avro.messages.MsgHeader header) {
    this.header = header;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return header;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: header = (com.incomplete.cubegs.common.avro.messages.MsgHeader)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'header' field.
   * @return Common messages header
   */
  public com.incomplete.cubegs.common.avro.messages.MsgHeader getHeader() {
    return header;
  }


  /**
   * Sets the value of the 'header' field.
   * Common messages header
   * @param value the value to set.
   */
  public void setHeader(com.incomplete.cubegs.common.avro.messages.MsgHeader value) {
    this.header = value;
  }

  /**
   * Creates a new MsgReceivedHeader RecordBuilder.
   * @return A new MsgReceivedHeader RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder();
  }

  /**
   * Creates a new MsgReceivedHeader RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MsgReceivedHeader RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder other) {
    if (other == null) {
      return new com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder();
    } else {
      return new com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder(other);
    }
  }

  /**
   * Creates a new MsgReceivedHeader RecordBuilder by copying an existing MsgReceivedHeader instance.
   * @param other The existing instance to copy.
   * @return A new MsgReceivedHeader RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader other) {
    if (other == null) {
      return new com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder();
    } else {
      return new com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder(other);
    }
  }

  /**
   * RecordBuilder for MsgReceivedHeader instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsgReceivedHeader>
    implements org.apache.avro.data.RecordBuilder<MsgReceivedHeader> {

    /** Common messages header */
    private com.incomplete.cubegs.common.avro.messages.MsgHeader header;
    private com.incomplete.cubegs.common.avro.messages.MsgHeader.Builder headerBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (other.hasHeaderBuilder()) {
        this.headerBuilder = com.incomplete.cubegs.common.avro.messages.MsgHeader.newBuilder(other.getHeaderBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing MsgReceivedHeader instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.header)) {
        this.header = data().deepCopy(fields()[0].schema(), other.header);
        fieldSetFlags()[0] = true;
      }
      this.headerBuilder = null;
    }

    /**
      * Gets the value of the 'header' field.
      * Common messages header
      * @return The value.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgHeader getHeader() {
      return header;
    }


    /**
      * Sets the value of the 'header' field.
      * Common messages header
      * @param value The value of 'header'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder setHeader(com.incomplete.cubegs.common.avro.messages.MsgHeader value) {
      validate(fields()[0], value);
      this.headerBuilder = null;
      this.header = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'header' field has been set.
      * Common messages header
      * @return True if the 'header' field has been set, false otherwise.
      */
    public boolean hasHeader() {
      return fieldSetFlags()[0];
    }

    /**
     * Gets the Builder instance for the 'header' field and creates one if it doesn't exist yet.
     * Common messages header
     * @return This builder.
     */
    public com.incomplete.cubegs.common.avro.messages.MsgHeader.Builder getHeaderBuilder() {
      if (headerBuilder == null) {
        if (hasHeader()) {
          setHeaderBuilder(com.incomplete.cubegs.common.avro.messages.MsgHeader.newBuilder(header));
        } else {
          setHeaderBuilder(com.incomplete.cubegs.common.avro.messages.MsgHeader.newBuilder());
        }
      }
      return headerBuilder;
    }

    /**
     * Sets the Builder instance for the 'header' field
     * Common messages header
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder setHeaderBuilder(com.incomplete.cubegs.common.avro.messages.MsgHeader.Builder value) {
      clearHeader();
      headerBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'header' field has an active Builder instance
     * Common messages header
     * @return True if the 'header' field has an active Builder instance
     */
    public boolean hasHeaderBuilder() {
      return headerBuilder != null;
    }

    /**
      * Clears the value of the 'header' field.
      * Common messages header
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgReceivedHeader.Builder clearHeader() {
      header = null;
      headerBuilder = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MsgReceivedHeader build() {
      try {
        MsgReceivedHeader record = new MsgReceivedHeader();
        if (headerBuilder != null) {
          try {
            record.header = this.headerBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("header"));
            throw e;
          }
        } else {
          record.header = fieldSetFlags()[0] ? this.header : (com.incomplete.cubegs.common.avro.messages.MsgHeader) defaultValue(fields()[0]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MsgReceivedHeader>
    WRITER$ = (org.apache.avro.io.DatumWriter<MsgReceivedHeader>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MsgReceivedHeader>
    READER$ = (org.apache.avro.io.DatumReader<MsgReceivedHeader>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    this.header.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.header == null) {
        this.header = new com.incomplete.cubegs.common.avro.messages.MsgHeader();
      }
      this.header.customDecode(in);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.header == null) {
            this.header = new com.incomplete.cubegs.common.avro.messages.MsgHeader();
          }
          this.header.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










