/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AlarmReportTypeEnum {
  ALARM_REPORT_ON_VALUE_CHANGE, ALARM_REPORT_ON_SEVERITY_CHANGE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlarmReportTypeEnum\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"symbols\":[\"ALARM_REPORT_ON_VALUE_CHANGE\",\"ALARM_REPORT_ON_SEVERITY_CHANGE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
