/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** This message indicates there is no more messages or data. It contains no comma at the end */
@org.apache.avro.specific.AvroGenerated
public class AvroNone extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5267842720193075976L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroNone\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"This message indicates there is no more messages or data. It contains no comma at the end\",\"fields\":[{\"name\":\"none_field\",\"type\":\"int\",\"doc\":\"End of include files\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** End of include files */
  @Deprecated public int none_field;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroNone() {}

  /**
   * All-args constructor.
   * @param none_field End of include files
   */
  public AvroNone(java.lang.Integer none_field) {
    this.none_field = none_field;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return none_field;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: none_field = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'none_field' field.
   * @return End of include files
   */
  public java.lang.Integer getNoneField() {
    return none_field;
  }

  /**
   * Sets the value of the 'none_field' field.
   * End of include files
   * @param value the value to set.
   */
  public void setNoneField(java.lang.Integer value) {
    this.none_field = value;
  }

  /**
   * Creates a new AvroNone RecordBuilder.
   * @return A new AvroNone RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.AvroNone.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.AvroNone.Builder();
  }

  /**
   * Creates a new AvroNone RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroNone RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.AvroNone.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.AvroNone.Builder other) {
    return new com.incomplete.cubegs.common.avro.messages.AvroNone.Builder(other);
  }

  /**
   * Creates a new AvroNone RecordBuilder by copying an existing AvroNone instance.
   * @param other The existing instance to copy.
   * @return A new AvroNone RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.AvroNone.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.AvroNone other) {
    return new com.incomplete.cubegs.common.avro.messages.AvroNone.Builder(other);
  }

  /**
   * RecordBuilder for AvroNone instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroNone>
    implements org.apache.avro.data.RecordBuilder<AvroNone> {

    /** End of include files */
    private int none_field;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.AvroNone.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.none_field)) {
        this.none_field = data().deepCopy(fields()[0].schema(), other.none_field);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroNone instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.AvroNone other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.none_field)) {
        this.none_field = data().deepCopy(fields()[0].schema(), other.none_field);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'none_field' field.
      * End of include files
      * @return The value.
      */
    public java.lang.Integer getNoneField() {
      return none_field;
    }

    /**
      * Sets the value of the 'none_field' field.
      * End of include files
      * @param value The value of 'none_field'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.AvroNone.Builder setNoneField(int value) {
      validate(fields()[0], value);
      this.none_field = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'none_field' field has been set.
      * End of include files
      * @return True if the 'none_field' field has been set, false otherwise.
      */
    public boolean hasNoneField() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'none_field' field.
      * End of include files
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.AvroNone.Builder clearNoneField() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public AvroNone build() {
      try {
        AvroNone record = new AvroNone();
        record.none_field = fieldSetFlags()[0] ? this.none_field : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
