/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** This record contains a list of key-value pairs */
@org.apache.avro.specific.AvroGenerated
public class ListKeyValues extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5271002746481403129L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ListKeyValues\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"This record contains a list of key-value pairs\",\"fields\":[{\"name\":\"listKeyValues\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"KeyValue\",\"doc\":\"A generic pair of key = value\",\"fields\":[{\"name\":\"key\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Key\"},{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Value\"}]}},\"doc\":\"List of key-value pairs\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** List of key-value pairs */
  @Deprecated public java.util.List<com.incomplete.cubegs.common.avro.messages.KeyValue> listKeyValues;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ListKeyValues() {}

  /**
   * All-args constructor.
   * @param listKeyValues List of key-value pairs
   */
  public ListKeyValues(java.util.List<com.incomplete.cubegs.common.avro.messages.KeyValue> listKeyValues) {
    this.listKeyValues = listKeyValues;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return listKeyValues;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: listKeyValues = (java.util.List<com.incomplete.cubegs.common.avro.messages.KeyValue>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'listKeyValues' field.
   * @return List of key-value pairs
   */
  public java.util.List<com.incomplete.cubegs.common.avro.messages.KeyValue> getListKeyValues() {
    return listKeyValues;
  }

  /**
   * Sets the value of the 'listKeyValues' field.
   * List of key-value pairs
   * @param value the value to set.
   */
  public void setListKeyValues(java.util.List<com.incomplete.cubegs.common.avro.messages.KeyValue> value) {
    this.listKeyValues = value;
  }

  /**
   * Creates a new ListKeyValues RecordBuilder.
   * @return A new ListKeyValues RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.ListKeyValues.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.ListKeyValues.Builder();
  }

  /**
   * Creates a new ListKeyValues RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ListKeyValues RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.ListKeyValues.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.ListKeyValues.Builder other) {
    return new com.incomplete.cubegs.common.avro.messages.ListKeyValues.Builder(other);
  }

  /**
   * Creates a new ListKeyValues RecordBuilder by copying an existing ListKeyValues instance.
   * @param other The existing instance to copy.
   * @return A new ListKeyValues RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.ListKeyValues.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.ListKeyValues other) {
    return new com.incomplete.cubegs.common.avro.messages.ListKeyValues.Builder(other);
  }

  /**
   * RecordBuilder for ListKeyValues instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ListKeyValues>
    implements org.apache.avro.data.RecordBuilder<ListKeyValues> {

    /** List of key-value pairs */
    private java.util.List<com.incomplete.cubegs.common.avro.messages.KeyValue> listKeyValues;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.ListKeyValues.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.listKeyValues)) {
        this.listKeyValues = data().deepCopy(fields()[0].schema(), other.listKeyValues);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ListKeyValues instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.ListKeyValues other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.listKeyValues)) {
        this.listKeyValues = data().deepCopy(fields()[0].schema(), other.listKeyValues);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'listKeyValues' field.
      * List of key-value pairs
      * @return The value.
      */
    public java.util.List<com.incomplete.cubegs.common.avro.messages.KeyValue> getListKeyValues() {
      return listKeyValues;
    }

    /**
      * Sets the value of the 'listKeyValues' field.
      * List of key-value pairs
      * @param value The value of 'listKeyValues'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.ListKeyValues.Builder setListKeyValues(java.util.List<com.incomplete.cubegs.common.avro.messages.KeyValue> value) {
      validate(fields()[0], value);
      this.listKeyValues = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'listKeyValues' field has been set.
      * List of key-value pairs
      * @return True if the 'listKeyValues' field has been set, false otherwise.
      */
    public boolean hasListKeyValues() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'listKeyValues' field.
      * List of key-value pairs
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.ListKeyValues.Builder clearListKeyValues() {
      listKeyValues = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public ListKeyValues build() {
      try {
        ListKeyValues record = new ListKeyValues();
        record.listKeyValues = fieldSetFlags()[0] ? this.listKeyValues : (java.util.List<com.incomplete.cubegs.common.avro.messages.KeyValue>) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
