/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Response to a check validity message (of the licence of a component). It returns true or false */
@org.apache.avro.specific.AvroGenerated
public class MsgCheckLicenceResponse extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7738985414384361546L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsgCheckLicenceResponse\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"Response to a check validity message (of the licence of a component). It returns true or false\",\"fields\":[{\"name\":\"componentId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Component identifier. It requests to check the licence\"},{\"name\":\"componentSignature\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Signature of the component\"},{\"name\":\"componentFunctions\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"List of functions to check whether they are licenced\"},{\"name\":\"licenceFunction\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"List of return values per function\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Component identifier. It requests to check the licence */
  @Deprecated public java.lang.String componentId;
  /** Signature of the component */
  @Deprecated public java.lang.String componentSignature;
  /** List of functions to check whether they are licenced */
  @Deprecated public java.util.List<java.lang.String> componentFunctions;
  /** List of return values per function */
  @Deprecated public java.util.List<java.lang.String> licenceFunction;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MsgCheckLicenceResponse() {}

  /**
   * All-args constructor.
   * @param componentId Component identifier. It requests to check the licence
   * @param componentSignature Signature of the component
   * @param componentFunctions List of functions to check whether they are licenced
   * @param licenceFunction List of return values per function
   */
  public MsgCheckLicenceResponse(java.lang.String componentId, java.lang.String componentSignature, java.util.List<java.lang.String> componentFunctions, java.util.List<java.lang.String> licenceFunction) {
    this.componentId = componentId;
    this.componentSignature = componentSignature;
    this.componentFunctions = componentFunctions;
    this.licenceFunction = licenceFunction;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return componentId;
    case 1: return componentSignature;
    case 2: return componentFunctions;
    case 3: return licenceFunction;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: componentId = (java.lang.String)value$; break;
    case 1: componentSignature = (java.lang.String)value$; break;
    case 2: componentFunctions = (java.util.List<java.lang.String>)value$; break;
    case 3: licenceFunction = (java.util.List<java.lang.String>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'componentId' field.
   * @return Component identifier. It requests to check the licence
   */
  public java.lang.String getComponentId() {
    return componentId;
  }

  /**
   * Sets the value of the 'componentId' field.
   * Component identifier. It requests to check the licence
   * @param value the value to set.
   */
  public void setComponentId(java.lang.String value) {
    this.componentId = value;
  }

  /**
   * Gets the value of the 'componentSignature' field.
   * @return Signature of the component
   */
  public java.lang.String getComponentSignature() {
    return componentSignature;
  }

  /**
   * Sets the value of the 'componentSignature' field.
   * Signature of the component
   * @param value the value to set.
   */
  public void setComponentSignature(java.lang.String value) {
    this.componentSignature = value;
  }

  /**
   * Gets the value of the 'componentFunctions' field.
   * @return List of functions to check whether they are licenced
   */
  public java.util.List<java.lang.String> getComponentFunctions() {
    return componentFunctions;
  }

  /**
   * Sets the value of the 'componentFunctions' field.
   * List of functions to check whether they are licenced
   * @param value the value to set.
   */
  public void setComponentFunctions(java.util.List<java.lang.String> value) {
    this.componentFunctions = value;
  }

  /**
   * Gets the value of the 'licenceFunction' field.
   * @return List of return values per function
   */
  public java.util.List<java.lang.String> getLicenceFunction() {
    return licenceFunction;
  }

  /**
   * Sets the value of the 'licenceFunction' field.
   * List of return values per function
   * @param value the value to set.
   */
  public void setLicenceFunction(java.util.List<java.lang.String> value) {
    this.licenceFunction = value;
  }

  /**
   * Creates a new MsgCheckLicenceResponse RecordBuilder.
   * @return A new MsgCheckLicenceResponse RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder();
  }

  /**
   * Creates a new MsgCheckLicenceResponse RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MsgCheckLicenceResponse RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder other) {
    return new com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder(other);
  }

  /**
   * Creates a new MsgCheckLicenceResponse RecordBuilder by copying an existing MsgCheckLicenceResponse instance.
   * @param other The existing instance to copy.
   * @return A new MsgCheckLicenceResponse RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse other) {
    return new com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder(other);
  }

  /**
   * RecordBuilder for MsgCheckLicenceResponse instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsgCheckLicenceResponse>
    implements org.apache.avro.data.RecordBuilder<MsgCheckLicenceResponse> {

    /** Component identifier. It requests to check the licence */
    private java.lang.String componentId;
    /** Signature of the component */
    private java.lang.String componentSignature;
    /** List of functions to check whether they are licenced */
    private java.util.List<java.lang.String> componentFunctions;
    /** List of return values per function */
    private java.util.List<java.lang.String> licenceFunction;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.componentId)) {
        this.componentId = data().deepCopy(fields()[0].schema(), other.componentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.componentSignature)) {
        this.componentSignature = data().deepCopy(fields()[1].schema(), other.componentSignature);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.componentFunctions)) {
        this.componentFunctions = data().deepCopy(fields()[2].schema(), other.componentFunctions);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.licenceFunction)) {
        this.licenceFunction = data().deepCopy(fields()[3].schema(), other.licenceFunction);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MsgCheckLicenceResponse instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.componentId)) {
        this.componentId = data().deepCopy(fields()[0].schema(), other.componentId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.componentSignature)) {
        this.componentSignature = data().deepCopy(fields()[1].schema(), other.componentSignature);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.componentFunctions)) {
        this.componentFunctions = data().deepCopy(fields()[2].schema(), other.componentFunctions);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.licenceFunction)) {
        this.licenceFunction = data().deepCopy(fields()[3].schema(), other.licenceFunction);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'componentId' field.
      * Component identifier. It requests to check the licence
      * @return The value.
      */
    public java.lang.String getComponentId() {
      return componentId;
    }

    /**
      * Sets the value of the 'componentId' field.
      * Component identifier. It requests to check the licence
      * @param value The value of 'componentId'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder setComponentId(java.lang.String value) {
      validate(fields()[0], value);
      this.componentId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'componentId' field has been set.
      * Component identifier. It requests to check the licence
      * @return True if the 'componentId' field has been set, false otherwise.
      */
    public boolean hasComponentId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'componentId' field.
      * Component identifier. It requests to check the licence
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder clearComponentId() {
      componentId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'componentSignature' field.
      * Signature of the component
      * @return The value.
      */
    public java.lang.String getComponentSignature() {
      return componentSignature;
    }

    /**
      * Sets the value of the 'componentSignature' field.
      * Signature of the component
      * @param value The value of 'componentSignature'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder setComponentSignature(java.lang.String value) {
      validate(fields()[1], value);
      this.componentSignature = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'componentSignature' field has been set.
      * Signature of the component
      * @return True if the 'componentSignature' field has been set, false otherwise.
      */
    public boolean hasComponentSignature() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'componentSignature' field.
      * Signature of the component
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder clearComponentSignature() {
      componentSignature = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'componentFunctions' field.
      * List of functions to check whether they are licenced
      * @return The value.
      */
    public java.util.List<java.lang.String> getComponentFunctions() {
      return componentFunctions;
    }

    /**
      * Sets the value of the 'componentFunctions' field.
      * List of functions to check whether they are licenced
      * @param value The value of 'componentFunctions'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder setComponentFunctions(java.util.List<java.lang.String> value) {
      validate(fields()[2], value);
      this.componentFunctions = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'componentFunctions' field has been set.
      * List of functions to check whether they are licenced
      * @return True if the 'componentFunctions' field has been set, false otherwise.
      */
    public boolean hasComponentFunctions() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'componentFunctions' field.
      * List of functions to check whether they are licenced
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder clearComponentFunctions() {
      componentFunctions = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'licenceFunction' field.
      * List of return values per function
      * @return The value.
      */
    public java.util.List<java.lang.String> getLicenceFunction() {
      return licenceFunction;
    }

    /**
      * Sets the value of the 'licenceFunction' field.
      * List of return values per function
      * @param value The value of 'licenceFunction'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder setLicenceFunction(java.util.List<java.lang.String> value) {
      validate(fields()[3], value);
      this.licenceFunction = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'licenceFunction' field has been set.
      * List of return values per function
      * @return True if the 'licenceFunction' field has been set, false otherwise.
      */
    public boolean hasLicenceFunction() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'licenceFunction' field.
      * List of return values per function
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgCheckLicenceResponse.Builder clearLicenceFunction() {
      licenceFunction = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public MsgCheckLicenceResponse build() {
      try {
        MsgCheckLicenceResponse record = new MsgCheckLicenceResponse();
        record.componentId = fieldSetFlags()[0] ? this.componentId : (java.lang.String) defaultValue(fields()[0]);
        record.componentSignature = fieldSetFlags()[1] ? this.componentSignature : (java.lang.String) defaultValue(fields()[1]);
        record.componentFunctions = fieldSetFlags()[2] ? this.componentFunctions : (java.util.List<java.lang.String>) defaultValue(fields()[2]);
        record.licenceFunction = fieldSetFlags()[3] ? this.licenceFunction : (java.util.List<java.lang.String>) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
