/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** This message requests a TM Processor to process a raw frame and to generate a ProcessedFrame */
@org.apache.avro.specific.AvroGenerated
public class MsgProcessRawFrame extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4312490971295701759L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsgProcessRawFrame\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"This message requests a TM Processor to process a raw frame and to generate a ProcessedFrame\",\"fields\":[{\"name\":\"authorizationToken\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Authorization token\"},{\"name\":\"missionName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Mission identifier\"},{\"name\":\"containerName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Unique name of the container. It can be a layer name, subsystem name, etc.\"},{\"name\":\"rawFrame\",\"type\":\"bytes\",\"doc\":\"Array of bytes contain the raw frame\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Authorization token */
  @Deprecated public java.lang.String authorizationToken;
  /** Mission identifier */
  @Deprecated public java.lang.String missionName;
  /** Unique name of the container. It can be a layer name, subsystem name, etc. */
  @Deprecated public java.lang.String containerName;
  /** Array of bytes contain the raw frame */
  @Deprecated public java.nio.ByteBuffer rawFrame;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MsgProcessRawFrame() {}

  /**
   * All-args constructor.
   * @param authorizationToken Authorization token
   * @param missionName Mission identifier
   * @param containerName Unique name of the container. It can be a layer name, subsystem name, etc.
   * @param rawFrame Array of bytes contain the raw frame
   */
  public MsgProcessRawFrame(java.lang.String authorizationToken, java.lang.String missionName, java.lang.String containerName, java.nio.ByteBuffer rawFrame) {
    this.authorizationToken = authorizationToken;
    this.missionName = missionName;
    this.containerName = containerName;
    this.rawFrame = rawFrame;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return authorizationToken;
    case 1: return missionName;
    case 2: return containerName;
    case 3: return rawFrame;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: authorizationToken = (java.lang.String)value$; break;
    case 1: missionName = (java.lang.String)value$; break;
    case 2: containerName = (java.lang.String)value$; break;
    case 3: rawFrame = (java.nio.ByteBuffer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'authorizationToken' field.
   * @return Authorization token
   */
  public java.lang.String getAuthorizationToken() {
    return authorizationToken;
  }

  /**
   * Sets the value of the 'authorizationToken' field.
   * Authorization token
   * @param value the value to set.
   */
  public void setAuthorizationToken(java.lang.String value) {
    this.authorizationToken = value;
  }

  /**
   * Gets the value of the 'missionName' field.
   * @return Mission identifier
   */
  public java.lang.String getMissionName() {
    return missionName;
  }

  /**
   * Sets the value of the 'missionName' field.
   * Mission identifier
   * @param value the value to set.
   */
  public void setMissionName(java.lang.String value) {
    this.missionName = value;
  }

  /**
   * Gets the value of the 'containerName' field.
   * @return Unique name of the container. It can be a layer name, subsystem name, etc.
   */
  public java.lang.String getContainerName() {
    return containerName;
  }

  /**
   * Sets the value of the 'containerName' field.
   * Unique name of the container. It can be a layer name, subsystem name, etc.
   * @param value the value to set.
   */
  public void setContainerName(java.lang.String value) {
    this.containerName = value;
  }

  /**
   * Gets the value of the 'rawFrame' field.
   * @return Array of bytes contain the raw frame
   */
  public java.nio.ByteBuffer getRawFrame() {
    return rawFrame;
  }

  /**
   * Sets the value of the 'rawFrame' field.
   * Array of bytes contain the raw frame
   * @param value the value to set.
   */
  public void setRawFrame(java.nio.ByteBuffer value) {
    this.rawFrame = value;
  }

  /**
   * Creates a new MsgProcessRawFrame RecordBuilder.
   * @return A new MsgProcessRawFrame RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder();
  }

  /**
   * Creates a new MsgProcessRawFrame RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MsgProcessRawFrame RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder other) {
    return new com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder(other);
  }

  /**
   * Creates a new MsgProcessRawFrame RecordBuilder by copying an existing MsgProcessRawFrame instance.
   * @param other The existing instance to copy.
   * @return A new MsgProcessRawFrame RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame other) {
    return new com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder(other);
  }

  /**
   * RecordBuilder for MsgProcessRawFrame instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsgProcessRawFrame>
    implements org.apache.avro.data.RecordBuilder<MsgProcessRawFrame> {

    /** Authorization token */
    private java.lang.String authorizationToken;
    /** Mission identifier */
    private java.lang.String missionName;
    /** Unique name of the container. It can be a layer name, subsystem name, etc. */
    private java.lang.String containerName;
    /** Array of bytes contain the raw frame */
    private java.nio.ByteBuffer rawFrame;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.authorizationToken)) {
        this.authorizationToken = data().deepCopy(fields()[0].schema(), other.authorizationToken);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.missionName)) {
        this.missionName = data().deepCopy(fields()[1].schema(), other.missionName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.containerName)) {
        this.containerName = data().deepCopy(fields()[2].schema(), other.containerName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.rawFrame)) {
        this.rawFrame = data().deepCopy(fields()[3].schema(), other.rawFrame);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MsgProcessRawFrame instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.authorizationToken)) {
        this.authorizationToken = data().deepCopy(fields()[0].schema(), other.authorizationToken);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.missionName)) {
        this.missionName = data().deepCopy(fields()[1].schema(), other.missionName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.containerName)) {
        this.containerName = data().deepCopy(fields()[2].schema(), other.containerName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.rawFrame)) {
        this.rawFrame = data().deepCopy(fields()[3].schema(), other.rawFrame);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'authorizationToken' field.
      * Authorization token
      * @return The value.
      */
    public java.lang.String getAuthorizationToken() {
      return authorizationToken;
    }

    /**
      * Sets the value of the 'authorizationToken' field.
      * Authorization token
      * @param value The value of 'authorizationToken'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder setAuthorizationToken(java.lang.String value) {
      validate(fields()[0], value);
      this.authorizationToken = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'authorizationToken' field has been set.
      * Authorization token
      * @return True if the 'authorizationToken' field has been set, false otherwise.
      */
    public boolean hasAuthorizationToken() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'authorizationToken' field.
      * Authorization token
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder clearAuthorizationToken() {
      authorizationToken = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'missionName' field.
      * Mission identifier
      * @return The value.
      */
    public java.lang.String getMissionName() {
      return missionName;
    }

    /**
      * Sets the value of the 'missionName' field.
      * Mission identifier
      * @param value The value of 'missionName'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder setMissionName(java.lang.String value) {
      validate(fields()[1], value);
      this.missionName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'missionName' field has been set.
      * Mission identifier
      * @return True if the 'missionName' field has been set, false otherwise.
      */
    public boolean hasMissionName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'missionName' field.
      * Mission identifier
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder clearMissionName() {
      missionName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'containerName' field.
      * Unique name of the container. It can be a layer name, subsystem name, etc.
      * @return The value.
      */
    public java.lang.String getContainerName() {
      return containerName;
    }

    /**
      * Sets the value of the 'containerName' field.
      * Unique name of the container. It can be a layer name, subsystem name, etc.
      * @param value The value of 'containerName'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder setContainerName(java.lang.String value) {
      validate(fields()[2], value);
      this.containerName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'containerName' field has been set.
      * Unique name of the container. It can be a layer name, subsystem name, etc.
      * @return True if the 'containerName' field has been set, false otherwise.
      */
    public boolean hasContainerName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'containerName' field.
      * Unique name of the container. It can be a layer name, subsystem name, etc.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder clearContainerName() {
      containerName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'rawFrame' field.
      * Array of bytes contain the raw frame
      * @return The value.
      */
    public java.nio.ByteBuffer getRawFrame() {
      return rawFrame;
    }

    /**
      * Sets the value of the 'rawFrame' field.
      * Array of bytes contain the raw frame
      * @param value The value of 'rawFrame'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder setRawFrame(java.nio.ByteBuffer value) {
      validate(fields()[3], value);
      this.rawFrame = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'rawFrame' field has been set.
      * Array of bytes contain the raw frame
      * @return True if the 'rawFrame' field has been set, false otherwise.
      */
    public boolean hasRawFrame() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'rawFrame' field.
      * Array of bytes contain the raw frame
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgProcessRawFrame.Builder clearRawFrame() {
      rawFrame = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public MsgProcessRawFrame build() {
      try {
        MsgProcessRawFrame record = new MsgProcessRawFrame();
        record.authorizationToken = fieldSetFlags()[0] ? this.authorizationToken : (java.lang.String) defaultValue(fields()[0]);
        record.missionName = fieldSetFlags()[1] ? this.missionName : (java.lang.String) defaultValue(fields()[1]);
        record.containerName = fieldSetFlags()[2] ? this.containerName : (java.lang.String) defaultValue(fields()[2]);
        record.rawFrame = fieldSetFlags()[3] ? this.rawFrame : (java.nio.ByteBuffer) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
