/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** This message contains a generic response to any message. It contains; code - return code. 0 means no   error message - error message  */
@org.apache.avro.specific.AvroGenerated
public class MsgReturnData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 867464825265194843L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsgReturnData\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"This message contains a generic response to any message. It contains; code - return code. 0 means no   error message - error message \",\"fields\":[{\"name\":\"errorCode\",\"type\":\"int\",\"doc\":\"Error code\"},{\"name\":\"errorMessage\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Error message\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Error code */
  @Deprecated public int errorCode;
  /** Error message */
  @Deprecated public java.lang.String errorMessage;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MsgReturnData() {}

  /**
   * All-args constructor.
   * @param errorCode Error code
   * @param errorMessage Error message
   */
  public MsgReturnData(java.lang.Integer errorCode, java.lang.String errorMessage) {
    this.errorCode = errorCode;
    this.errorMessage = errorMessage;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return errorCode;
    case 1: return errorMessage;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: errorCode = (java.lang.Integer)value$; break;
    case 1: errorMessage = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'errorCode' field.
   * @return Error code
   */
  public java.lang.Integer getErrorCode() {
    return errorCode;
  }

  /**
   * Sets the value of the 'errorCode' field.
   * Error code
   * @param value the value to set.
   */
  public void setErrorCode(java.lang.Integer value) {
    this.errorCode = value;
  }

  /**
   * Gets the value of the 'errorMessage' field.
   * @return Error message
   */
  public java.lang.String getErrorMessage() {
    return errorMessage;
  }

  /**
   * Sets the value of the 'errorMessage' field.
   * Error message
   * @param value the value to set.
   */
  public void setErrorMessage(java.lang.String value) {
    this.errorMessage = value;
  }

  /**
   * Creates a new MsgReturnData RecordBuilder.
   * @return A new MsgReturnData RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder();
  }

  /**
   * Creates a new MsgReturnData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MsgReturnData RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder other) {
    return new com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder(other);
  }

  /**
   * Creates a new MsgReturnData RecordBuilder by copying an existing MsgReturnData instance.
   * @param other The existing instance to copy.
   * @return A new MsgReturnData RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgReturnData other) {
    return new com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder(other);
  }

  /**
   * RecordBuilder for MsgReturnData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsgReturnData>
    implements org.apache.avro.data.RecordBuilder<MsgReturnData> {

    /** Error code */
    private int errorCode;
    /** Error message */
    private java.lang.String errorMessage;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.errorCode)) {
        this.errorCode = data().deepCopy(fields()[0].schema(), other.errorCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[1].schema(), other.errorMessage);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MsgReturnData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgReturnData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.errorCode)) {
        this.errorCode = data().deepCopy(fields()[0].schema(), other.errorCode);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.errorMessage)) {
        this.errorMessage = data().deepCopy(fields()[1].schema(), other.errorMessage);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'errorCode' field.
      * Error code
      * @return The value.
      */
    public java.lang.Integer getErrorCode() {
      return errorCode;
    }

    /**
      * Sets the value of the 'errorCode' field.
      * Error code
      * @param value The value of 'errorCode'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder setErrorCode(int value) {
      validate(fields()[0], value);
      this.errorCode = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'errorCode' field has been set.
      * Error code
      * @return True if the 'errorCode' field has been set, false otherwise.
      */
    public boolean hasErrorCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'errorCode' field.
      * Error code
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder clearErrorCode() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'errorMessage' field.
      * Error message
      * @return The value.
      */
    public java.lang.String getErrorMessage() {
      return errorMessage;
    }

    /**
      * Sets the value of the 'errorMessage' field.
      * Error message
      * @param value The value of 'errorMessage'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder setErrorMessage(java.lang.String value) {
      validate(fields()[1], value);
      this.errorMessage = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'errorMessage' field has been set.
      * Error message
      * @return True if the 'errorMessage' field has been set, false otherwise.
      */
    public boolean hasErrorMessage() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'errorMessage' field.
      * Error message
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgReturnData.Builder clearErrorMessage() {
      errorMessage = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public MsgReturnData build() {
      try {
        MsgReturnData record = new MsgReturnData();
        record.errorCode = fieldSetFlags()[0] ? this.errorCode : (java.lang.Integer) defaultValue(fields()[0]);
        record.errorMessage = fieldSetFlags()[1] ? this.errorMessage : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
