/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** This message removes a new ground station */
@org.apache.avro.specific.AvroGenerated
public class MsgRemoveGroundStation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5301280189862095616L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MsgRemoveGroundStation\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"This message removes a new ground station\",\"fields\":[{\"name\":\"authorizationToken\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Authorization token\"},{\"name\":\"groundStationName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Ground Station identifier\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Authorization token */
  @Deprecated public java.lang.String authorizationToken;
  /** Ground Station identifier */
  @Deprecated public java.lang.String groundStationName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MsgRemoveGroundStation() {}

  /**
   * All-args constructor.
   * @param authorizationToken Authorization token
   * @param groundStationName Ground Station identifier
   */
  public MsgRemoveGroundStation(java.lang.String authorizationToken, java.lang.String groundStationName) {
    this.authorizationToken = authorizationToken;
    this.groundStationName = groundStationName;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return authorizationToken;
    case 1: return groundStationName;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: authorizationToken = (java.lang.String)value$; break;
    case 1: groundStationName = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'authorizationToken' field.
   * @return Authorization token
   */
  public java.lang.String getAuthorizationToken() {
    return authorizationToken;
  }

  /**
   * Sets the value of the 'authorizationToken' field.
   * Authorization token
   * @param value the value to set.
   */
  public void setAuthorizationToken(java.lang.String value) {
    this.authorizationToken = value;
  }

  /**
   * Gets the value of the 'groundStationName' field.
   * @return Ground Station identifier
   */
  public java.lang.String getGroundStationName() {
    return groundStationName;
  }

  /**
   * Sets the value of the 'groundStationName' field.
   * Ground Station identifier
   * @param value the value to set.
   */
  public void setGroundStationName(java.lang.String value) {
    this.groundStationName = value;
  }

  /**
   * Creates a new MsgRemoveGroundStation RecordBuilder.
   * @return A new MsgRemoveGroundStation RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder();
  }

  /**
   * Creates a new MsgRemoveGroundStation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MsgRemoveGroundStation RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder other) {
    return new com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder(other);
  }

  /**
   * Creates a new MsgRemoveGroundStation RecordBuilder by copying an existing MsgRemoveGroundStation instance.
   * @param other The existing instance to copy.
   * @return A new MsgRemoveGroundStation RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation other) {
    return new com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder(other);
  }

  /**
   * RecordBuilder for MsgRemoveGroundStation instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MsgRemoveGroundStation>
    implements org.apache.avro.data.RecordBuilder<MsgRemoveGroundStation> {

    /** Authorization token */
    private java.lang.String authorizationToken;
    /** Ground Station identifier */
    private java.lang.String groundStationName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.authorizationToken)) {
        this.authorizationToken = data().deepCopy(fields()[0].schema(), other.authorizationToken);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.groundStationName)) {
        this.groundStationName = data().deepCopy(fields()[1].schema(), other.groundStationName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MsgRemoveGroundStation instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.authorizationToken)) {
        this.authorizationToken = data().deepCopy(fields()[0].schema(), other.authorizationToken);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.groundStationName)) {
        this.groundStationName = data().deepCopy(fields()[1].schema(), other.groundStationName);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'authorizationToken' field.
      * Authorization token
      * @return The value.
      */
    public java.lang.String getAuthorizationToken() {
      return authorizationToken;
    }

    /**
      * Sets the value of the 'authorizationToken' field.
      * Authorization token
      * @param value The value of 'authorizationToken'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder setAuthorizationToken(java.lang.String value) {
      validate(fields()[0], value);
      this.authorizationToken = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'authorizationToken' field has been set.
      * Authorization token
      * @return True if the 'authorizationToken' field has been set, false otherwise.
      */
    public boolean hasAuthorizationToken() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'authorizationToken' field.
      * Authorization token
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder clearAuthorizationToken() {
      authorizationToken = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'groundStationName' field.
      * Ground Station identifier
      * @return The value.
      */
    public java.lang.String getGroundStationName() {
      return groundStationName;
    }

    /**
      * Sets the value of the 'groundStationName' field.
      * Ground Station identifier
      * @param value The value of 'groundStationName'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder setGroundStationName(java.lang.String value) {
      validate(fields()[1], value);
      this.groundStationName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'groundStationName' field has been set.
      * Ground Station identifier
      * @return True if the 'groundStationName' field has been set, false otherwise.
      */
    public boolean hasGroundStationName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'groundStationName' field.
      * Ground Station identifier
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.MsgRemoveGroundStation.Builder clearGroundStationName() {
      groundStationName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public MsgRemoveGroundStation build() {
      try {
        MsgRemoveGroundStation record = new MsgRemoveGroundStation();
        record.authorizationToken = fieldSetFlags()[0] ? this.authorizationToken : (java.lang.String) defaultValue(fields()[0]);
        record.groundStationName = fieldSetFlags()[1] ? this.groundStationName : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
