/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum RadixEnum {
  RADIX_NONE, RADIX_DECIMAL, RADIX_HEXADECIMAL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RadixEnum\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"symbols\":[\"RADIX_NONE\",\"RADIX_DECIMAL\",\"RADIX_HEXADECIMAL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
