/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** It defines a value assigned to an argument of a TC */
@org.apache.avro.specific.AvroGenerated
public class TC_ArgumentAssignment extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8441904942364756415L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TC_ArgumentAssignment\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"It defines a value assigned to an argument of a TC\",\"fields\":[{\"name\":\"tcName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"TC name\"},{\"name\":\"argument\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Argument name\"},{\"name\":\"value\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Argument value\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** TC name */
  @Deprecated public java.lang.String tcName;
  /** Argument name */
  @Deprecated public java.lang.String argument;
  /** Argument value */
  @Deprecated public java.lang.String value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TC_ArgumentAssignment() {}

  /**
   * All-args constructor.
   * @param tcName TC name
   * @param argument Argument name
   * @param value Argument value
   */
  public TC_ArgumentAssignment(java.lang.String tcName, java.lang.String argument, java.lang.String value) {
    this.tcName = tcName;
    this.argument = argument;
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return tcName;
    case 1: return argument;
    case 2: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: tcName = (java.lang.String)value$; break;
    case 1: argument = (java.lang.String)value$; break;
    case 2: value = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tcName' field.
   * @return TC name
   */
  public java.lang.String getTcName() {
    return tcName;
  }

  /**
   * Sets the value of the 'tcName' field.
   * TC name
   * @param value the value to set.
   */
  public void setTcName(java.lang.String value) {
    this.tcName = value;
  }

  /**
   * Gets the value of the 'argument' field.
   * @return Argument name
   */
  public java.lang.String getArgument() {
    return argument;
  }

  /**
   * Sets the value of the 'argument' field.
   * Argument name
   * @param value the value to set.
   */
  public void setArgument(java.lang.String value) {
    this.argument = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return Argument value
   */
  public java.lang.String getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * Argument value
   * @param value the value to set.
   */
  public void setValue(java.lang.String value) {
    this.value = value;
  }

  /**
   * Creates a new TC_ArgumentAssignment RecordBuilder.
   * @return A new TC_ArgumentAssignment RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder();
  }

  /**
   * Creates a new TC_ArgumentAssignment RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TC_ArgumentAssignment RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder other) {
    return new com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder(other);
  }

  /**
   * Creates a new TC_ArgumentAssignment RecordBuilder by copying an existing TC_ArgumentAssignment instance.
   * @param other The existing instance to copy.
   * @return A new TC_ArgumentAssignment RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment other) {
    return new com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder(other);
  }

  /**
   * RecordBuilder for TC_ArgumentAssignment instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TC_ArgumentAssignment>
    implements org.apache.avro.data.RecordBuilder<TC_ArgumentAssignment> {

    /** TC name */
    private java.lang.String tcName;
    /** Argument name */
    private java.lang.String argument;
    /** Argument value */
    private java.lang.String value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.tcName)) {
        this.tcName = data().deepCopy(fields()[0].schema(), other.tcName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.argument)) {
        this.argument = data().deepCopy(fields()[1].schema(), other.argument);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.value)) {
        this.value = data().deepCopy(fields()[2].schema(), other.value);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TC_ArgumentAssignment instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.tcName)) {
        this.tcName = data().deepCopy(fields()[0].schema(), other.tcName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.argument)) {
        this.argument = data().deepCopy(fields()[1].schema(), other.argument);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.value)) {
        this.value = data().deepCopy(fields()[2].schema(), other.value);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'tcName' field.
      * TC name
      * @return The value.
      */
    public java.lang.String getTcName() {
      return tcName;
    }

    /**
      * Sets the value of the 'tcName' field.
      * TC name
      * @param value The value of 'tcName'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder setTcName(java.lang.String value) {
      validate(fields()[0], value);
      this.tcName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'tcName' field has been set.
      * TC name
      * @return True if the 'tcName' field has been set, false otherwise.
      */
    public boolean hasTcName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'tcName' field.
      * TC name
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder clearTcName() {
      tcName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'argument' field.
      * Argument name
      * @return The value.
      */
    public java.lang.String getArgument() {
      return argument;
    }

    /**
      * Sets the value of the 'argument' field.
      * Argument name
      * @param value The value of 'argument'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder setArgument(java.lang.String value) {
      validate(fields()[1], value);
      this.argument = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'argument' field has been set.
      * Argument name
      * @return True if the 'argument' field has been set, false otherwise.
      */
    public boolean hasArgument() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'argument' field.
      * Argument name
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder clearArgument() {
      argument = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * Argument value
      * @return The value.
      */
    public java.lang.String getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * Argument value
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder setValue(java.lang.String value) {
      validate(fields()[2], value);
      this.value = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * Argument value
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'value' field.
      * Argument value
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TC_ArgumentAssignment.Builder clearValue() {
      value = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public TC_ArgumentAssignment build() {
      try {
        TC_ArgumentAssignment record = new TC_ArgumentAssignment();
        record.tcName = fieldSetFlags()[0] ? this.tcName : (java.lang.String) defaultValue(fields()[0]);
        record.argument = fieldSetFlags()[1] ? this.argument : (java.lang.String) defaultValue(fields()[1]);
        record.value = fieldSetFlags()[2] ? this.value : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
