/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
/** Definition of a Condition that a TM Frame shall meet */
@org.apache.avro.specific.AvroGenerated
public class TM_FrameCondition extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1920491330449983629L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TM_FrameCondition\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"doc\":\"Definition of a Condition that a TM Frame shall meet\",\"fields\":[{\"name\":\"frameName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of the TM Frame this condition belongs to\"},{\"name\":\"parameterName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of the parameter\"},{\"name\":\"parameterValue\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Value the parameter must have\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Name of the TM Frame this condition belongs to */
  @Deprecated public java.lang.String frameName;
  /** Name of the parameter */
  @Deprecated public java.lang.String parameterName;
  /** Value the parameter must have */
  @Deprecated public java.lang.String parameterValue;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TM_FrameCondition() {}

  /**
   * All-args constructor.
   * @param frameName Name of the TM Frame this condition belongs to
   * @param parameterName Name of the parameter
   * @param parameterValue Value the parameter must have
   */
  public TM_FrameCondition(java.lang.String frameName, java.lang.String parameterName, java.lang.String parameterValue) {
    this.frameName = frameName;
    this.parameterName = parameterName;
    this.parameterValue = parameterValue;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return frameName;
    case 1: return parameterName;
    case 2: return parameterValue;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: frameName = (java.lang.String)value$; break;
    case 1: parameterName = (java.lang.String)value$; break;
    case 2: parameterValue = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'frameName' field.
   * @return Name of the TM Frame this condition belongs to
   */
  public java.lang.String getFrameName() {
    return frameName;
  }

  /**
   * Sets the value of the 'frameName' field.
   * Name of the TM Frame this condition belongs to
   * @param value the value to set.
   */
  public void setFrameName(java.lang.String value) {
    this.frameName = value;
  }

  /**
   * Gets the value of the 'parameterName' field.
   * @return Name of the parameter
   */
  public java.lang.String getParameterName() {
    return parameterName;
  }

  /**
   * Sets the value of the 'parameterName' field.
   * Name of the parameter
   * @param value the value to set.
   */
  public void setParameterName(java.lang.String value) {
    this.parameterName = value;
  }

  /**
   * Gets the value of the 'parameterValue' field.
   * @return Value the parameter must have
   */
  public java.lang.String getParameterValue() {
    return parameterValue;
  }

  /**
   * Sets the value of the 'parameterValue' field.
   * Value the parameter must have
   * @param value the value to set.
   */
  public void setParameterValue(java.lang.String value) {
    this.parameterValue = value;
  }

  /**
   * Creates a new TM_FrameCondition RecordBuilder.
   * @return A new TM_FrameCondition RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder newBuilder() {
    return new com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder();
  }

  /**
   * Creates a new TM_FrameCondition RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TM_FrameCondition RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder other) {
    return new com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder(other);
  }

  /**
   * Creates a new TM_FrameCondition RecordBuilder by copying an existing TM_FrameCondition instance.
   * @param other The existing instance to copy.
   * @return A new TM_FrameCondition RecordBuilder
   */
  public static com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder newBuilder(com.incomplete.cubegs.common.avro.messages.TM_FrameCondition other) {
    return new com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder(other);
  }

  /**
   * RecordBuilder for TM_FrameCondition instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TM_FrameCondition>
    implements org.apache.avro.data.RecordBuilder<TM_FrameCondition> {

    /** Name of the TM Frame this condition belongs to */
    private java.lang.String frameName;
    /** Name of the parameter */
    private java.lang.String parameterName;
    /** Value the parameter must have */
    private java.lang.String parameterValue;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.frameName)) {
        this.frameName = data().deepCopy(fields()[0].schema(), other.frameName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.parameterName)) {
        this.parameterName = data().deepCopy(fields()[1].schema(), other.parameterName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.parameterValue)) {
        this.parameterValue = data().deepCopy(fields()[2].schema(), other.parameterValue);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TM_FrameCondition instance
     * @param other The existing instance to copy.
     */
    private Builder(com.incomplete.cubegs.common.avro.messages.TM_FrameCondition other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.frameName)) {
        this.frameName = data().deepCopy(fields()[0].schema(), other.frameName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.parameterName)) {
        this.parameterName = data().deepCopy(fields()[1].schema(), other.parameterName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.parameterValue)) {
        this.parameterValue = data().deepCopy(fields()[2].schema(), other.parameterValue);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'frameName' field.
      * Name of the TM Frame this condition belongs to
      * @return The value.
      */
    public java.lang.String getFrameName() {
      return frameName;
    }

    /**
      * Sets the value of the 'frameName' field.
      * Name of the TM Frame this condition belongs to
      * @param value The value of 'frameName'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder setFrameName(java.lang.String value) {
      validate(fields()[0], value);
      this.frameName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'frameName' field has been set.
      * Name of the TM Frame this condition belongs to
      * @return True if the 'frameName' field has been set, false otherwise.
      */
    public boolean hasFrameName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'frameName' field.
      * Name of the TM Frame this condition belongs to
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder clearFrameName() {
      frameName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'parameterName' field.
      * Name of the parameter
      * @return The value.
      */
    public java.lang.String getParameterName() {
      return parameterName;
    }

    /**
      * Sets the value of the 'parameterName' field.
      * Name of the parameter
      * @param value The value of 'parameterName'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder setParameterName(java.lang.String value) {
      validate(fields()[1], value);
      this.parameterName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'parameterName' field has been set.
      * Name of the parameter
      * @return True if the 'parameterName' field has been set, false otherwise.
      */
    public boolean hasParameterName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'parameterName' field.
      * Name of the parameter
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder clearParameterName() {
      parameterName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'parameterValue' field.
      * Value the parameter must have
      * @return The value.
      */
    public java.lang.String getParameterValue() {
      return parameterValue;
    }

    /**
      * Sets the value of the 'parameterValue' field.
      * Value the parameter must have
      * @param value The value of 'parameterValue'.
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder setParameterValue(java.lang.String value) {
      validate(fields()[2], value);
      this.parameterValue = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'parameterValue' field has been set.
      * Value the parameter must have
      * @return True if the 'parameterValue' field has been set, false otherwise.
      */
    public boolean hasParameterValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'parameterValue' field.
      * Value the parameter must have
      * @return This builder.
      */
    public com.incomplete.cubegs.common.avro.messages.TM_FrameCondition.Builder clearParameterValue() {
      parameterValue = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public TM_FrameCondition build() {
      try {
        TM_FrameCondition record = new TM_FrameCondition();
        record.frameName = fieldSetFlags()[0] ? this.frameName : (java.lang.String) defaultValue(fields()[0]);
        record.parameterName = fieldSetFlags()[1] ? this.parameterName : (java.lang.String) defaultValue(fields()[1]);
        record.parameterValue = fieldSetFlags()[2] ? this.parameterValue : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
