/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.incomplete.cubegs.common.avro.messages;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TriggerEnum {
  ALGORITHM_TRIGGER_NONE, ALGORITHM_ON_PARAMETER_UPDATE, ALGORITHM_ON_INPUT_PARAMETER_UPDATE, ALGORITHM_ON_PERIODIC_RATE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TriggerEnum\",\"namespace\":\"com.incomplete.cubegs.common.avro.messages\",\"symbols\":[\"ALGORITHM_TRIGGER_NONE\",\"ALGORITHM_ON_PARAMETER_UPDATE\",\"ALGORITHM_ON_INPUT_PARAMETER_UPDATE\",\"ALGORITHM_ON_PERIODIC_RATE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
