.PHONY: clean All

All:
	@echo "----------Building project:[ Common - Debug ]----------"
	@cd "Common" && "$(MAKE)" -f  "Common.mk" PreBuild && "$(MAKE)" -f  "Common.mk"
clean:
	@echo "----------Cleaning project:[ Common - Debug ]----------"
	@cd "Common" && "$(MAKE)" -f  "Common.mk" clean
